#!/bin/bash

sudo pacman -S xorg \
       stow \
       vim \
       emacs \
       git \
       ranger \
       dunst \
       newsboat \
       lxappearance \
       arandr \
       sxiv \
       feh \
       firefox \
       xcompmgr \
			 xwallpaper \
			 xclip
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
